### PR TITLE
Simplifying user creation

### PR DESCRIPTION
**Pull request by dmvolod**

### CODE REVIEW

**Comment by karesti** [comment]
thanks @dmvolod !

**Comment by dmvolod** [comment]
@karesti do you have a plans to merge this PR, I don't have a right to commit this repo

**Comment by karesti** [comment]
> @karesti do you have a plans to merge this PR, I don't have a right to commit this repo

yes, I wanted yesterday :) but github was not behaving well :) 
could you please resolve the conflict ?

**Comment by dmvolod** [comment]
Fixed

**Comment by karesti** [comment]
thanks @dmvolod !

**Pull request merged**
